@API_HostAddress = http://localhost:5044


// USER

### Create
POST {{API_HostAddress}}/api/user
Content-Type: application/json

{
  "title": "email1",
  "typeCode": "EMAIL",
  "currentStatus": "SENT"
}

### Get all
GET {{API_HostAddress}}/api/user/communications

### Get by Id
GET {{API_HostAddress}}/api/user/c42cc59d-8133-4335-97a0-042918a068ad

### Update
POST {{API_HostAddress}}/api/user/c42cc59d-8133-4335-97a0-042918a068ad/status
Content-Type: application/json

{
  "statusCode": "DRAFT"
}

### Get all
GET {{API_HostAddress}}/api/user/types


// ADMIN

### Create
POST {{API_HostAddress}}/api/admin
Content-Type: application/json

{
  "typeCode": "SC",
  "displayName": "Snap Chat",
  "communicationTypeStatuses": [
    {
      "typeCode": "SC",
      "statusCode": "SENT",
      "description": "Sent"
    },
    {
      "typeCode": "SC",
      "statusCode": "OPENED",
      "description": "Opened"
    }
  ]
}

### Update
POST {{API_HostAddress}}/api/admin/SC
Content-Type: application/json

{
  "typeCode": "SC",
  "displayName": "Snap Chat",
  "communicationTypeStatuses": [
    {
      "typeCode": "SC",
      "statusCode": "SENT",
      "description": "Sent"
    },
    {
      "typeCode": "SC",
      "statusCode": "CLOSED",
      "description": "Closed"
    }
  ]
}